export const GET_LEADS_REQUEST = 'GET_LEADS_REQUEST'
export const GET_LEADS_SUCCESS = 'GET_LEADS_SUCCESS'
export const GET_LEADS_ERROR = 'GET_LEADS_ERROR'

export const ADD_LEAD_REQUEST = 'ADD_LEAD_REQUEST'
export const ADD_LEAD_SUCCESS = 'ADD_LEAD_SUCCESS'
export const ADD_LEAD_ERROR =   'ADD_LEAD_ERROR'

export const REMOVE_LEAD_REQUEST = 'REMOVE_LEAD_REQUEST'
export const REMOVE_LEAD_SUCCESS = 'REMOVE_LEAD_SUCCESS'
export const REMOVE_LEAD_ERROR =   'REMOVE_LEAD_ERROR'